### PR TITLE
feat(plugin): make every round four turns long

### PR DESCRIPTION
**Pull request by anarchuser**
There are inconsistencies and issues due to the fact that the number of turns in a round depended on the number of colors still in the game.
Thus, with this, every round consists of exactly four turns

### CODE REVIEW

**Comment by anarchuser** [comment]
Note: Documentation needs to be updated appropriately

**Review by SKoschnicke — COMMENTED** [review]
Looks good, but with this change, it seems that colors which can't make a move aren't marked in the GUI anymore:
image
(only yellow can make moves, so I would expect the overlay with the "No move possible" message over the other colors blocks).

**Comment by anarchuser** [comment]
I'll look into it. It's probably due to a change in how colors are accessed and might just require a small adjustment in the GUI

**Comment by anarchuser** [comment]
I've changed `orderedColors` to always consist of all four colors (since every color gets a turn per round now, valid or not) and introduced `validColors` to check if a color is invalid or not.
Thus this requires an adjustment in the GUI

**Comment by anarchuser** [comment]
After this is merged, I'll update https://github.com/CAU-Kiel-Tech-Inf/gui/pull/59 accordingly

**Review by SKoschnicke — APPROVED** [review]
Can't test with GUI, though.

**Pull request merged**
